baseURL = "https://example.org/"
languageCode = "en-us"
title = "jwhogg"
# theme = ["hugo-notice", "cactus"]
theme = ["typo", "hugo-notice"]


[params]
# Meta description
description = "Joel's Personal Website"
gtm_id = "G-VHFF3CGGEV"

# Appearance settings
theme = 'light'

# Intro on main page, content is markdown
homeIntroTitle = "Hi, I'm Joel 👋"
homeIntroContent = """
This is a space for me to post notes, research, and longer articles on a varitey of subjects- mostly keeping within tech.

Recently, I've been deep-diving the word2vec literature, and am working on implementing it using numpy. I've also been working on a budgeting app with banking integration.
"""
homeImage = true

# Collection to display on home
homeCollectionTitle = 'Articles'
homeCollection = 'articles'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "linkedin"
url = "www.linkedin.com/in/joel-w-hogg"

# [[params.social]]
# name = "medium"
# url = "https://medium.com/@user"

[[params.social]]
name = "github"
url = "https://github.com/jwhogg"

[[params.social]]
name = "email"
url = "mailto:joelhogg45@gmail.com"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "articles"
url = "/articles"

# [[params.menu]]
# name = "about"
# url = "/about"

[[params.menu]]
name = "portfolio"
url = "/portfolio"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"